window.CRF_LOCATIONS = [
  {
    id: "charles-santore-library",
    name: "Charles Santore Library",
    type: "Library",
    address: "932 S 7th St, Philadelphia, PA 19147",
    neighborhood: "Bella Vista",
    zip: "19147",
    lat: 39.9382,
    lng: -75.1545,
    distance: 0.7,
    verified: "July 2026",
    transit: "Routes 47 and 57",
    website: "",
    phone: "",
    notes: "Demonstration record. Verify hours and services before traveling.",
    features: {
      stepFree: "confirmed",
      restroom: "reported",
      seating: "confirmed",
      quiet: "reported",
      airConditioning: "confirmed",
      cleanAir: "unknown",
      water: "confirmed",
      power: "reported"
    }
  },
  {
    id: "philadelphia-city-institute-library",
    name: "Philadelphia City Institute Library",
    type: "Library",
    address: "1905 Locust St, Philadelphia, PA 19103",
    neighborhood: "Rittenhouse",
    zip: "19103",
    lat: 39.9491,
    lng: -75.1732,
    distance: 1.4,
    verified: "July 2026",
    transit: "Routes 9, 12, 21, and 42",
    website: "",
    phone: "",
    notes: "Demonstration record. Verify hours and services before traveling.",
    features: {
      stepFree: "confirmed",
      restroom: "unknown",
      seating: "confirmed",
      quiet: "confirmed",
      airConditioning: "confirmed",
      cleanAir: "unknown",
      water: "reported",
      power: "reported"
    }
  },
  {
    id: "south-philadelphia-library",
    name: "South Philadelphia Library",
    type: "Library",
    address: "1700 S Broad St, Philadelphia, PA 19145",
    neighborhood: "Point Breeze",
    zip: "19145",
    lat: 39.9283,
    lng: -75.1696,
    distance: 1.8,
    verified: "July 2026",
    transit: "Broad Street Line and Route 4",
    website: "",
    phone: "",
    notes: "Demonstration record. Verify hours and services before traveling.",
    features: {
      stepFree: "confirmed",
      restroom: "confirmed",
      seating: "confirmed",
      quiet: "reported",
      airConditioning: "confirmed",
      cleanAir: "reported",
      water: "confirmed",
      power: "confirmed"
    }
  },
  {
    id: "lucien-blackwell-library",
    name: "Lucien E. Blackwell West Philadelphia Regional Library",
    type: "Library",
    address: "125 S 52nd St, Philadelphia, PA 19139",
    neighborhood: "West Philadelphia",
    zip: "19139",
    lat: 39.9573,
    lng: -75.2253,
    distance: 4.8,
    verified: "July 2026",
    transit: "Market-Frankford Line and Route 52",
    website: "",
    phone: "",
    notes: "Demonstration record. Verify hours and services before traveling.",
    features: {
      stepFree: "confirmed",
      restroom: "confirmed",
      seating: "confirmed",
      quiet: "reported",
      airConditioning: "confirmed",
      cleanAir: "unknown",
      water: "confirmed",
      power: "reported"
    }
  },
  {
    id: "kingsessing-recreation-center",
    name: "Kingsessing Recreation Center",
    type: "Recreation center",
    address: "4901 Kingsessing Ave, Philadelphia, PA 19143",
    neighborhood: "Kingsessing",
    zip: "19143",
    lat: 39.9429,
    lng: -75.218,
    distance: 4.2,
    verified: "Demonstration record",
    transit: "Trolley Routes 13 and 34",
    website: "",
    phone: "",
    notes: "Demonstration record. Verify hours and services before traveling.",
    features: {
      stepFree: "reported",
      restroom: "reported",
      seating: "confirmed",
      quiet: "unknown",
      airConditioning: "reported",
      cleanAir: "unknown",
      water: "reported",
      power: "unknown"
    }
  },
  {
    id: "lloyd-hall",
    name: "Lloyd Hall",
    type: "Community space",
    address: "1 Boathouse Row, Philadelphia, PA 19130",
    neighborhood: "Fairmount",
    zip: "19130",
    lat: 39.9692,
    lng: -75.1862,
    distance: 2.7,
    verified: "Demonstration record",
    transit: "Routes 7, 32, and 48",
    website: "",
    phone: "",
    notes: "Demonstration record. Verify hours and services before traveling.",
    features: {
      stepFree: "reported",
      restroom: "reported",
      seating: "reported",
      quiet: "unknown",
      airConditioning: "unknown",
      cleanAir: "unknown",
      water: "reported",
      power: "unknown"
    }
  }
];
